# Generated by Django 4.0.2 on 2022-02-13 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trellis', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('name', 'owner')},
        ),
    ]
