# Generated by Django 4.0.2 on 2022-02-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellis', '0003_alter_crop_options_alter_crop_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planting',
            name='name',
            field=models.CharField(default='Planting Name', max_length=300),
            preserve_default=False,
        ),
    ]
