# Generated by Django 4.0.2 on 2022-02-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellis', '0004_planting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='seeds_per_feet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='seeds_per_plant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
